server:
  port: 8081
  servlet:
    context-path: /sikabox

spring:
  datasource:
      password: admin123
      url: jdbc:mysql://localhost:3306/expatswap
      username: root
  jpa:
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            ddl-auto: update
        show-sql: true

validId: true
